name: Publish Tag to Dockerhub

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB }}
    - uses: actions/checkout@v2
    - name: Run Build script
      run: ./build.sh
